// DO NOT EDIT THIS FILE DIRECTLY, IT IS
// AUTOGENERATED BY /scripts/extract-sass-vars.js
export const colors = {
  lightblue: "#a2b8ff",
  darkblue: "#6276b4",
  red: "#f54b5e",
  orange: "#ef7d2c",
  yellow: "#f8c51c",
  green: "#37c491",
  sherwoodgreen: "#01482f",
  riogrande: "#c4d800",
  lighgrey: "#eee3e3",
  cyan: "#eee3e3",
  dark: "#2e2e2e",
  neutralDark30: "#2e2e2e",
  neutralDark50: "#2e2e2e",
  neutralDark70: "#2e2e2e",
  light: "#f7f0f0",
  neutralLight30: "#f7f0f0",
  neutralLight50: "#f7f0f0",
  neutralLight70: "#f7f0f0",
  primary: "#ef7d2c",
  secondary: "#01482f",
  tertiary: "#c4d800",
  success: "#37c491",
  info: "#eee3e3",
  warning: "#f8c51c",
  danger: "#f54b5e",
  disable: "#eee3e3",
};

export default colors;
